version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
    rust: "1.82"

branches:
  only:
    - main
tags:
  only:
    - "v*.*.*"  

sphinx:
  configuration: docs/conf.py

python:
  install:
    #    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
         - doc
formats:
  - pdf

